### PR TITLE
vendor: update compose-go to v2.0.0-rc.8

### PR DESCRIPTION
**Pull request by crazy-max**
full diff: https://github.com/compose-spec/compose-go/compare/v2.0.0-rc.3...v2.0.0-rc.8

### CODE REVIEW

**Comment by crazy-max** [comment]
@glours Any ETA for v2.0.0?

**Comment by glours** [comment]
@crazy-max soon, I think we fixed all the issues reported by users with this last release candidate

**Review by glours — APPROVED** [review]
LGTM

**Comment by crazy-max** [comment]
Needs follow-up when v2.0.0 released

**Pull request merged**
