### PR TITLE
build: return imageID when loading without docker driver

### LINKED ISSUE #420: --iidfile contains mismatching id
The documentation for `build` argument `--iidfile` states: `--iidfile, Write the image ID to the file`.
The image imported to docker does not correspond to the iidfile contents.

When using:
```
docker buildx build --tag kalamaja --load --iidfile id --progress plain .
```
On dockerfile:

```
FROM alpine
RUN echo a
```

```
...
#6 exporting manifest sha256:305dbeb87452bc1457231f97e698d19db38c61def97a7a2982e6eae83256f7b6 0.0s done
#6 exporting config sha256:e384d63460089a5a38d739dc1fd82092caaaff3c158c324faae54ffda974a455 0.0s done
#6 sending tarball
#6 sending tarball 0.4s done
#6 DONE 0.8s

#7 importing to docker
#7 DONE 0.2s
```

The result is:
```
# cat id; echo
sha256:305dbeb87452bc1457231f97e698d19db38c61def97a7a2982e6eae83256f7b6
```
```
# docker image ls | head -2
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
kalamaja            latest              e384d6346008        3 minutes ago       5.57MB
```
```
# docker image inspect e384d6346008 | jq .[0].Id
"sha256:e384d63460089a5a38d739dc1fd82092caaaff3c158c324faae54ffda974a455"
```

### PR DESCRIPTION
**Pull request by crazy-max**
fixes #420 

follow-up https://github.com/docker/buildx/pull/975#issuecomment-1053957423

repro https://github.com/crazy-max/buildx-buildkit-tests/runs/5374641648?check_suite_focus=true#step:7:2

Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>

### CODE REVIEW

**Review by tonistiigi — COMMENTED** [review]
We should just use `containerimage.config.digest` always and if it is not set (eg. multi-platform) then the full digest as before.

No need to do anything special for `--load` as multi-platform don't load anyway.

Also need to make sure this doesn't break the github action and update if it may.

**Comment by crazy-max** [comment]
> Also need to make sure this doesn't break the github action and update if it may.

It's fine for the GitHub Action with this behavior but as discussed we might create a new output named `imageid` that will contain the actual imageid and set `digest` output accordingly.

**Review by tonistiigi — APPROVED** [review]

**Comment by tonistiigi** [comment]
> It's fine for the GitHub Action with this behavior but as discussed we might create a new output named imageid that will contain the actual imageid and set digest output accordingly.

But what field does the action use atm? If it uses `iidfile` then it needs to be updated before the release.

**Comment by crazy-max** [comment]
Hum yeah atm `digest` output returns content of `iidfile`, so need to make changes for the action. Will do that.

**Review by tonistiigi — APPROVED** [review]

**Pull request merged**
