### PR TITLE
deps: update buildkit, vendor changes

### PR DESCRIPTION
**Pull request by jsternberg**

### CODE REVIEW

**Comment by jedevc** [comment]
cc @thaJeztah since updates to docker/cli :smile:

**Comment by thaJeztah** [comment]
Overall looks fine, but before merging, you could consider having a look at https://github.com/moby/buildkit/pull/4523 - if that's merged, you could update moby and docker/cli to v25.0.0-rc.1


The tricky bit is that neither docker/cli nor moby/moby are a module yet, so currently it requires "manual" compare of the vendor.mod from these repositories; one dependency that looks to be "behind" is Cobra; in docker/cli we updated to 1.8. CI looks green so it's not critical, and I'm happy to do a follow-up to align some f the remaining modules.

**Comment by thaJeztah** [comment]
@jsternberg https://github.com/moby/buildkit/pull/4523 was merged, so you can consider updating to current master 👍

**Review by thaJeztah — APPROVED** [review]
Thanks!

LGTM (nb)

**Review by tonistiigi — APPROVED** [review]

**Pull request merged**
