### PR TITLE
README.md: add usage of tonistiigi/binfmt

### PR DESCRIPTION
**Pull request by AkihiroSuda**

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
@tonistiigi PTAL

**Comment by AkihiroSuda** [comment]
@tonistiigi @tiborvass PTAL

**Comment by tonistiigi** [comment]
@AkihiroSuda I recommend https://github.com/tonistiigi/binfmt#installing-emulators

**Comment by AkihiroSuda** [comment]
updated

**Pull request merged**
