### PR TITLE
vendor: update compose-go to v1.19.0

### PR DESCRIPTION
**Pull request by dvdksn**
Signed-off-by: David Karlsson <35727626+dvdksn@users.noreply.github.com>

Bake is currently broken for projects with a `compose.yaml` that implements the latest version of the compose spec (the one used by Docker Compose v1.22)

### CODE REVIEW

**Comment by crazy-max** [comment]
Can we have a test similar to https://github.com/docker/buildx/pull/1971/commits/b01693f63ee420586b004683f9ae770dfaee5c8d?

I think in this is case we want to test the `develop` section: https://github.com/compose-spec/compose-go/pull/461

**Comment by crazy-max** [comment]
Added extra commit to test with `develop` section.

**Review by crazy-max — APPROVED** [review]
PTAL @glours

**Review by glours — APPROVED** [review]
LGTM 👍 , Thanks @dvdksn 🙏

**Pull request merged**
