### PR TITLE
update to go1.21.6

### PR DESCRIPTION
**Pull request by thaJeztah**

### CODE REVIEW

**Review by tonistiigi — APPROVED** [review]
@crazy-max Can we go back to feature release tags? The actual version can be looked up from provenance if needed.

**Comment by crazy-max** [comment]
> @crazy-max Can we go back to feature release tags? The actual version can be looked up from provenance if needed.

Yes I think that's fine.

@thaJeztah Ok to switch to `1.21`?

**Comment by thaJeztah** [comment]
I can change, but wondering what the big issue is; we pin all dependencies by version (so have to maintain those versions), wondering why Go has to be an exception for that.

**Comment by crazy-max** [comment]
A patch releases signal changes that don't affect the public API. It guarantees backward compatibility and stability. But a security issue in the specification or implementation may come to light whose resolution requires breaking compatibility in a patch release though. So yeah I see what you mean.

**Pull request merged**
