### PR TITLE
Fix tolerations not parsing its options correctly, update docs regarding quoted driver options

### PR DESCRIPTION
**Pull request by szeber**
Followup for #1045. Updates the docs with correct examples on how to quote multiple node selectors or tolerations and removes unquoting from the tolerations, since the CSV parser that parses the driver-opts already handles unquoting.

### CODE REVIEW

**Comment by szeber** [comment]
@tonistiigi @AkihiroSuda this should fix the issue raised by @ktaborski in #1045

**Comment by AkihiroSuda** [comment]
Can we have a unit test?

**Comment by ktaborski** [comment]
@AkihiroSuda @szeber any updates regarding this?

**Comment by ddelange** [comment]
FYI, when I quote as suggested here (running current `master`), I get an obscure `invalid syntax` error. Not sure if related as it's the first time I'm trying out the kubernetes driver (and we only have nodes with taints)

```console
# wrong quotes
$ /usr/bin/docker buildx create --name builder-aead224e-ed8e-49fc-ad7c-b7232da1b586 --driver kubernetes --driver-opt tolerations="key=arch,value=arm64,operator=Equal,effect=NoSchedule" --driver-opt namespace=docker-buildx --driver-opt replicas=1 --driver-opt requests.cpu=1m --driver-opt limits.memory=2Gi --driver-opt nodeselector=kubernetes.io/arch=arm64 --driver-opt rootless=true --driver-opt qemu.install=true --buildkitd-flags --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host --use
  error: parse error on line 1, column 13: bare " in non-quoted-field

...

# wrong quotes
$ /usr/bin/docker buildx create --name builder-84bc1c8c-e0a5-48d8-9269-409422fa4490 --driver kubernetes --driver-opt 'tolerations="key=arch,value=arm64,operator=Equal,effect=NoSchedule"' --driver-opt namespace=docker-buildx --driver-opt replicas=1 --driver-opt requests.cpu=1m --driver-opt limits.memory=2Gi --driver-opt nodeselector=kubernetes.io/arch=arm64 --driver-opt rootless=true --driver-opt qemu.install=true --buildkitd-flags --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host --use
  error: parse error on line 1, column 14: bare " in non-quoted-field

...

# wrong quotes
$ /usr/bin/docker buildx create --name builder-123f035e-7fcc-4c81-b046-8ffadcb12833 --driver kubernetes --driver-opt "tolerations=\"key=arch,value=arm64,operator=Equal,effect=NoSchedule\"" --driver-opt namespace=docker-buildx --driver-opt replicas=1 --driver-opt requests.cpu=1m --driver-opt limits.memory=2Gi --driver-opt nodeselector=kubernetes.io/arch=arm64 --driver-opt rootless=true --driver-opt qemu.install=true --buildkitd-flags --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host --use
  error: parse error on line 1, column 15: extraneous or missing " in quoted-field

...

# quotes as suggested here, getting invalid syntax error
$ /usr/bin/docker buildx create --name builder-12f140fa-5dd7-45f7-87b2-59ceacbfe3fb --driver kubernetes --driver-opt "tolerations=key=arch,value=arm64,operator=Equal,effect=NoSchedule" --driver-opt namespace=docker-buildx --driver-opt replicas=1 --driver-opt requests.cpu=1m --driver-opt limits.memory=2Gi --driver-opt nodeselector=kubernetes.io/arch=arm64 --driver-opt rootless=true --driver-opt qemu.install=true --buildkitd-flags --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host --use
  builder-12f140fa-5dd7-45f7-87b2-59ceacbfe3fb
$ /usr/bin/docker buildx inspect --bootstrap --builder builder-12f140fa-5dd7-45f7-87b2-59ceacbfe3fb
  Name:   builder-12f140fa-5dd7-45f7-87b2-59ceacbfe3fb
  Driver: kubernetes
  
  Nodes:
  Name:            builder-12f140fa-5dd7-45f7-87b2-59ceacbfe3fb0
  Endpoint:        kubernetes:///builder-12f140fa-5dd7-45f7-87b2-59ceacbfe3fb?deployment=&kubeconfig=
  Driver Options:  limits.memory=2Gi
  ,                namespace=docker-buildx
  ,                nodeselector=kubernetes.io/arch=arm64
  ,                qemu.install=true
  ,                replicas=1
  ,                requests.cpu=1m
  ,                rootless=true
  ,                tolerations=key=arch,value=arm64,operator=Equal,effect=NoSchedule
  Error:           invalid syntax
$ /usr/bin/docker buildx bake --file docker-compose.yml --set *.platform=linux/amd64 --set *.platform=linux/arm64 --metadata-file /tmp/docker-build-push-orx3PF/metadata-file
error: no valid drivers found: invalid syntax
```

**Comment by szeber** [comment]
hey, i'll try to get a test in this today

**Comment by AkihiroSuda** [comment]
Please squash commits

**Comment by szeber** [comment]
@AkihiroSuda squashed

**Comment by ddelange** [comment]
@szeber could you fix merge conflicts?

**Comment by szeber** [comment]
@ddelange fixed, it was fixing the same bug as i was :D

**Review by tonistiigi — APPROVED** [review]

**Review by AkihiroSuda — APPROVED** [review]

**Comment by ddelange** [comment]
@crazy-max is there an expected release date planned?

**Pull request merged**
