### PR TITLE
go.mod: update cli-docs-tool v0.5.1

### PR DESCRIPTION
**Pull request by thaJeztah**
follow-up to https://github.com/docker/buildx/pull/1493

### CODE REVIEW

**Comment by thaJeztah** [comment]
Rebased this one, as https://github.com/docker/buildx/pull/1493 was merged

@crazy-max let me know if you want me to squash these two commits; _technically_ the first one is "invalid" as it doesn't contain the updated files, but thought it was easier to review when kept separate

**Comment by crazy-max** [comment]
@thaJeztah Yes I think it would be better to squash :+1:

**Comment by thaJeztah** [comment]
👍 squashed

**Comment by thaJeztah** [comment]
opened backport as well; https://github.com/docker/buildx/pull/1496

**Review by crazy-max — APPROVED** [review]

**Pull request merged**
