### PR TITLE
docs: use absolute links and update link targets

### PR DESCRIPTION
**Pull request by dvdksn**
Signed-off-by: David Karlsson <35727626+dvdksn@users.noreply.github.com>

### CODE REVIEW

**Comment by dvdksn** [comment]
Docs upstream workflow will be broken until main is updated

**Review by crazy-max — APPROVED** [review]

**Review by tonistiigi — COMMENTED** [review]
Is this absolutely needed? It breaks the links when viewing md files in github.

**Comment by dvdksn** [comment]
Alternatively we patch cli-docs-tool to rewrite the links when generating yaml. @thaJeztah had the same concern. But that could be something for a follow-up I think.

**Comment by thaJeztah** [comment]
> Alternatively we patch cli-docs-tool to rewrite the links when generating yaml. @thaJeztah had the same concern. But that could be something for a follow-up I think.

- related discussion here; https://github.com/docker/cli/pull/4866#discussion_r1484428260

**Review by crazy-max — APPROVED** [review]

**Pull request merged**
