### PR TITLE
Add option to build/bake to override instance

### PR DESCRIPTION
**Pull request by cpuguy83**
This helps prevent race conditions with concurrent build invocations.

### CODE REVIEW

**Comment by tonistiigi** [comment]
I think this should be a global flag. Eg. like `docker` has `--context` on every command.  Not sure about the flag name, something now quite right about `--use` but can't think of anything better. @tiborvass

**Comment by tonistiigi** [comment]
And if you have time, I guess it would be good to have env for this as well.

**Comment by cpuguy83** [comment]
Every other command, I think, already accepts an argument for the build instance.

**Comment by tonistiigi** [comment]
Not every command. eg https://github.com/docker/buildx/pull/249 does not. I think ENV would be very useful for this.

**Comment by cpuguy83** [comment]
This is updated with the discussed changes.

**Pull request merged**
