### PR TITLE
(drivers): Introduce a client interface

### PR DESCRIPTION
**Pull request by silvin-lubecki**
This client abstracts from buildkit client. This will allow further enhancement like caching remote driver responses.

### CODE REVIEW

**Comment by jedevc** [comment]
Could it be worth pulling in the interface into buildkit, something like this: https://github.com/moby/buildkit/pull/3820? It might help to avoid type drift over time? I know I closed the above since we don't want to support multiple different types of clients, but maybe this wrapping use case (for cached remote driver responses) could be the reason to want it?

**Comment by silvin-lubecki** [comment]
> Could it be worth pulling in the interface into buildkit
I don't know about this, it doesn't fit with golang idioms about interfaces. API Consumers should own their own set of interfaces, which are most of the time a subset of the external dependency type.

**Comment by tonistiigi** [comment]
I think `Client()` should always return a buildkit client. If we need any custom behavior in the implementation of specific drivers, we can add more methods to the `Driver` interface. Making these behaviors as a side effect of some buildkit client functions makes it so that buildx does not know anymore when the connection to BuildKit is actually established which can lead to unexpected pauses in the UX, differences in how drivers behave, or buildx needing to know that in some cases "buildkit client" (that is not real buildkit client anymore) behaves differently than expected.

**Comment by silvin-lubecki** [comment]
Sorry didn't mean to merge this one ...

**Comment by silvin-lubecki** [comment]
https://github.com/docker/buildx/pull/2072 to undo it, sorry 🙏

**Pull request merged**
