### PR TITLE
Dockerfile: update to docker v27.4.0

### PR DESCRIPTION
**Pull request by thaJeztah**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Updated to rc.4

**Comment by thaJeztah** [comment]
Updated to v27.4.0

**Review by crazy-max — APPROVED** [review]

**Comment by crazy-max** [comment]
> @crazy-max any ideas on this failure? Is it somehow building for the wrong arch, or picking up cache for the wrong one?
> 
> ```
> 25 [linux/amd64->windows/arm64 buildx-build 1/1] RUN --mount=type=bind,target=.   --mount=type=cache,target=/root/.cache   --mount=type=cache,target=/go/pkg/mod   --mount=type=bind,from=buildx-version,source=/buildx-version,target=/buildx-version <<EOT (set -e...)
> #25 0.068 + CGO_ENABLED=0 go build -mod vendor -trimpath -ldflags '-X github.com/docker/buildx/version.Version=df70f75 -X github.com/docker/buildx/version.Revision=df70f7519b6457f68692c0a14423d47667536db5 -X github.com/docker/buildx/version.Package=github.com/docker/buildx -s -w' -o /usr/bin/docker-buildx ./cmd/buildx
> #25 61.93 /usr/bin/docker-buildx: PE32+ executable for MS Windows 6.01 (console), ARM64, 6 sections
> #25 61.95 file /usr/bin/docker-buildx does not match expected target architecture arm64: PE32+ executable for MS Windows 6.01 (console), ARM64, 6 sections
> #25 ERROR: process "/bin/sh -c   set -e\n  xx-go --wrap\n  DESTDIR=/usr/bin VERSION=$(cat /buildx-version/version) REVISION=$(cat /buildx-version/revision) GO_EXTRA_LDFLAGS=\"-s -w\" ./hack/build\n  file /usr/bin/docker-buildx\n  xx-verify --static /usr/bin/docker-buildx\n" did not complete successfully: exit code: 1
> ------
>  > [linux/amd64->windows/arm64 buildx-build 1/1] RUN --mount=type=bind,target=.   --mount=type=cache,target=/root/.cache   --mount=type=cache,target=/go/pkg/mod   --mount=type=bind,from=buildx-version,source=/buildx-version,target=/buildx-version <<EOT (set -e...):
> 0.068 + CGO_ENABLED=0 go build -mod vendor -trimpath -ldflags '-X github.com/docker/buildx/version.Version=df70f75 -X github.com/docker/buildx/version.Revision=df70f7519b6457f68692c0a14423d47667536db5 -X github.com/docker/buildx/version.Package=github.com/docker/buildx -s -w' -o /usr/bin/docker-buildx ./cmd/buildx
> 61.93 /usr/bin/docker-buildx: PE32+ executable for MS Windows 6.01 (console), ARM64, 6 sections
> 61.95 file /usr/bin/docker-buildx does not match expected target architecture arm64: PE32+ executable for MS Windows 6.01 (console), ARM64, 6 sections
> ------
> Dockerfile:76
> --------------------
>   75 |     ARG GO_EXTRA_FLAGS
>   76 | >>> RUN --mount=type=bind,target=. \
>   77 | >>>   --mount=type=cache,target=/root/.cache \
>   78 | >>>   --mount=type=cache,target=/go/pkg/mod \
>   79 | >>>   --mount=type=bind,from=buildx-version,source=/buildx-version,target=/buildx-version <<EOT
>   80 | >>>   set -e
>   81 | >>>   xx-go --wrap
>   82 | >>>   DESTDIR=/usr/bin VERSION=$(cat /buildx-version/version) REVISION=$(cat /buildx-version/revision) GO_EXTRA_LDFLAGS="-s -w" ./hack/build
>   83 | >>>   file /usr/bin/docker-buildx
>   84 | >>>   xx-verify --static /usr/bin/docker-buildx
>   85 | >>> EOT
>   86 |     
> --------------------
> ERROR: failed to solve: process "/bin/sh -c   set -e\n  xx-go --wrap\n  DESTDIR=/usr/bin VERSION=$(cat /buildx-version/version) REVISION=$(cat /buildx-version/revision) GO_EXTRA_LDFLAGS=\"-s -w\" ./hack/build\n  file /usr/bin/docker-buildx\n  xx-verify --static /usr/bin/docker-buildx\n" did not complete successfully: exit code: 1
> make: *** [Makefile:35: release] Error 1
> Error: Process completed with exit code 2.
> ```

Yes this is similar to https://github.com/tonistiigi/xx/pull/174#issuecomment-2523454100 :cry:

**Comment by thaJeztah** [comment]
Rebased; looks happy now 👍

**Pull request merged**
