### PR TITLE
bake: merge targets on same groups

### LINKED ISSUE #133: merging compose files
for the following workflow
https://github.com/FernandoMiguel/BuildKit/blob/master/.github/workflows/main.yml

we build with the merge of two compose files
`docker-buildx bake -f docker-compose.yml -f buildx.yml`

one contains php and nginx services, and the other overrides the php dockerfile
https://github.com/FernandoMiguel/BuildKit/blob/master/buildx.yml

if the nginx service isn't in the override file, it isn't build
here is a build with `--print`
https://github.com/FernandoMiguel/BuildKit/commit/ff56b967241dc321ac9fd841b11c68aedad17545/checks

### PR DESCRIPTION
**Pull request by tonistiigi**
fixes #133 

Workaround is to name all the targets in the command line

@FernandoMiguel 

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

### CODE REVIEW

**Comment by FernandoMiguel** [comment]
@tonistiigi does the array support more than one override?

**Comment by tonistiigi** [comment]
@FernandoMiguel You can have as many override files as you want

**Comment by FernandoMiguel** [comment]
@tonistiigi perfect
Will test tomorrow

**Comment by FernandoMiguel** [comment]
tested here
https://github.com/FernandoMiguel/BuildKit/commit/3912767c5e11a55ba356b045735461b6c6665a5e/checks

I can see the expected merge

**Pull request merged**
