### PR TITLE
RFC: releases add shasum create for releases bin files

### PR DESCRIPTION
**Pull request by MaxPeal**
the Binary release files are used in many CIs
so shasums and / or gpg sigs are Best Practices.

possible fix for #285 
feedback about the PR is welcome

### CODE REVIEW

**Comment by tonistiigi** [comment]
@MaxPeal CI is not passing.

One problem with this is that we don't have signing/notary for Darwin integrated in CI atm and that is needed to run binaries in newer macos. The way we have done last releases is that after CI has built it I manually pull and sign the mac binary. So with this in mind please exclude darwin binary from the shasums (I guess signing acts as a verification replacement for it anyway)

**Comment by MaxPeal** [comment]
@tonistiigi can you give me a info, about the directory in witch the binaries really are after the full build process, befor it get deployed?

**Comment by tonistiigi** [comment]
In release-out https://github.com/docker/buildx/blob/master/.travis.yml#L29

**Comment by MaxPeal** [comment]
@tonistiigi 
mmm ok, but its not exist after the run is finischd befor the demploment, if i see it corect:
https://travis-ci.org/github/docker/buildx/jobs/694724212#L1517

**Comment by MaxPeal** [comment]
or should i add the creation of the hashum to
https://github.com/docker/buildx/blob/master/Dockerfile#L59
and not to the .travis.yml?

**Comment by tonistiigi** [comment]
We have moved away from travis. Please reopen if you have updated the PR

**Pull request closed without merging**
