### PR TITLE
Bump containerd/console to use console.File instead of os.File

### PR DESCRIPTION
**Pull request by ulyssessouza**
This PR just changes the signature of `NewPrinter` to use `console.File` instead of `os.File` to allow other structs to be passed. 
Check https://github.com/docker/app/pull/779

### CODE REVIEW

**Comment by tonistiigi** [comment]
@ulyssessouza CI doesn't seem to like it. Did you run `make vendor` to update vendor in containers?

**Comment by ulyssessouza** [comment]
@tonistiigi I just did a `go mod vendor`. I've just pushed it again after the `make vendor`

**Comment by tonistiigi** [comment]
@ulyssessouza Seems new `sys` broke windows build:

```
#56 376.6 vendor/github.com/docker/docker/pkg/system/filesys_windows.go:111:24: cannot use uintptr(unsafe.Pointer(&sd[0])) (type uintptr) as type *"golang.org/x/sys/windows".SECURITY_DESCRIPTOR in assignment
```

**Comment by tonistiigi** [comment]
That change seems to be done in moby already, just `docker/docker` dependency needs to be updated as well.

**Comment by tonistiigi** [comment]
@ulyssessouza Not sure if you're still working on it but that doesn't seem to be the correct version. Looks like docker was actually downgraded in your last push.

**Comment by ulyssessouza** [comment]
@tonistiigi I don't know why, but github just closed the PR and didn't want to reopen, so I created another one https://github.com/docker/buildx/pull/207 .
Sorry for that :(

**Pull request closed without merging**
