### PR TITLE
migrate reference github.com/distribution/reference

### PR DESCRIPTION
**Pull request by thaJeztah**
- [x] depends on https://github.com/docker/buildx/pull/2031
- relates to https://github.com/moby/buildkit/pull/4188

The "reference" package was moved to a separate module, which was extracted from https://github.com/distribution/distribution/commit/b9b19409cf458dcb9e1253ff44ba75bd0620faa6

### CODE REVIEW

**Comment by thaJeztah** [comment]
I split this in 2 commits; the first one is updating to the "previous" compose-go, and the second commit only contains the changes related to migrating to the new dependency (which includes a patch-bump of compose-go)

**Review by glours — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@tonistiigi @crazy-max PTAL 🤗

**Review by crazy-max — APPROVED** [review]

**Comment by thaJeztah** [comment]
This one good to go, or do we need more reviewers? 😅

**Pull request merged**
