### PR TITLE
[TAR-853] ADDED .fossa file for fossa scans

### PR DESCRIPTION
**Pull request by zelahi**
Added a .fossa file for the build-cli

### CODE REVIEW

**Comment by zelahi** [comment]
@dave-tucker @docker/tools-and-release-engineering

**Comment by dave-tucker** [comment]
@zelahi FOSSA LGTM but you've picked up someone else's commit on this PR somehow

**Comment by zelahi** [comment]
o strange, let me see if I can fix that

**Comment by thaJeztah** [comment]
make sure your local repo is up to date with upstream, then doing a rebase should make it disappear

**Pull request merged**
