### PR TITLE
docs: fix broken link in buildx_bake CLI reference

### PR DESCRIPTION
**Pull request by dvdksn**

### CODE REVIEW

**Review by crazy-max — COMMENTED** [review]
I see other refs: https://github.com/search?q=repo%3Adocker%2Fbuildx%20customize%2Fbake&type=code :eyes:

**Comment by dvdksn** [comment]
I grepped for this.. Aaaargh. I mustve had a typo. Updating

**Comment by dvdksn** [comment]
```
#0 0.054 - ./_site/engine/reference/commandline/plugin_ls/index.html
#0 0.054   *  linking to internal hash #filter that does not exist (line 142)
#0 0.054      <a href="#filter">filtering</a>
```
???

**Comment by crazy-max** [comment]
@dvdksn Looks to be the same as https://github.com/docker/buildx/pull/1512#issuecomment-1381910608. Should be fixed upstream I guess. cc @thaJeztah

**Review by jedevc — APPROVED** [review]

**Pull request merged**
