### PR TITLE
OpenTelemetry support

### PR DESCRIPTION
**Pull request by tonistiigi**
Depends on:
- ~https://github.com/moby/buildkit/pull/2163~
- ~cli incompatible with moby master~

```
docker run -d --name jaeger  -p 6831:6831/udp -p 16686:16686 jaegertracing/all-in-one
docker buildx create --driver-opt network=host --driver-opt image=moby/buildkit:master --driver-opt env.JAEGER_TRACE=localhost:6831
```

### CODE REVIEW

**Comment by crazy-max** [comment]
Just tested myself, works great.

image

Not related to this PR but I also encountered an issue that seems linked to moby/buildkit#2162: `SendMsg called after CloseSend`

[79ec0a42e37a50928d8911c2682f691a.json.zip](https://github.com/docker/buildx/files/6764021/79ec0a42e37a50928d8911c2682f691a.json.zip)

**Comment by tonistiigi** [comment]
@crazy-max Do you have a reproducer for this as haven't seen this myself. Not a blocker for this PR but create a tracking issue in Buildkit if you do.

**Comment by crazy-max** [comment]
Yes I have a reproducer on a public repo. Will create an issue on BuildKit repo.

**Comment by crazy-max** [comment]
@tonistiigi Looks like it has been fixed, can repro anymore with `moby/buildkit:v0.9.0-rc1`.

**Comment by morlay** [comment]
Nice feature!

log with traceID and spanID will be better. https://github.com/moby/buildkit/pull/2235

**Comment by tonistiigi** [comment]
@crazy-max Might be flaky. Don't know any change in the past days.

**Review by crazy-max — APPROVED** [review]

**Comment by drefixs** [comment]
when i use docker context with remote SSH I also have the next error
```
docker buildx build .
...
[+] Building 0.0s (0/0)
WARN[0000] commandConn.CloseWrite: commandconn: failed to wait: signal: killed
WARN[0000] commandConn.CloseRead: commandconn: failed to wait: signal: killed
WARN[0000] commandConn.CloseWrite: commandconn: failed to wait: signal: killed
[+] Building 0.0s (0/0)
error: failed to get status: rpc error: code = Unavailable desc = connection error: desc = "transport: failed to write client preface: write |1: broken pipe"
74637 v0.6.1-docker /usr/local/lib/docker/cli-plugins/docker-buildx --debug buildx build --platform linux/amd64 .
github.com/moby/buildkit/client.(*Client).solve.func4
	/go/src/github.com/docker/buildx/vendor/github.com/moby/buildkit/client/solve.go:249
golang.org/x/sync/errgroup.(*Group).Go.func1
	/go/src/github.com/docker/buildx/vendor/golang.org/x/sync/errgroup/errgroup.go:57
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1371
```

only change that was done for this part of code is replacing opentracing to opentelemetry lib

https://github.com/docker/buildx/pull/635/files#diff-74fa88d40f7782eb5e6f983186505885f739f01689d78de9f486dbd69b8d2b26R97

**Comment by tonistiigi** [comment]
@bobrik @drefixs #741

**Pull request merged**
