### PR TITLE
bump compose-go to v2.1.1

### PR DESCRIPTION
**Pull request by glours**
Use the latest version `v2.1.0` of `compose-go` with `bake`.
~This one introduces `entitlements` attribute which is managed on the Compose side~

### CODE REVIEW

**Comment by tonistiigi** [comment]
> This one introduces entitlements attribute which is managed on the Compose side

I don't think this actually works with bake as I don't see the values passed through, or am I missing something?

Also, not sure if we should enable this (without some explicit insecure-mode opt-in) before https://github.com/docker/buildx/issues/179

**Comment by crazy-max** [comment]
@glours Looks like [2.1.1](https://github.com/compose-spec/compose-go/releases/tag/v2.1.1) is out, can you bump to this version instead? Thanks.

**Review by crazy-max — APPROVED** [review]

**Comment by glours** [comment]
Hahah @crazy-max  I just see your message, is it too late to bump the version?

**Comment by crazy-max** [comment]
> Hahah @crazy-max I just see your message, is it too late to bump the version?

No worries I bumped it myself, see last commit.

**Pull request merged**
