### PR TITLE
vendor: vendor with -compat=1.17

### PR DESCRIPTION
**Pull request by thaJeztah**
This might break compatibility with projects using this module that
are still on go1.16, which is EOL, so probably ok to ignore:

    github.com/docker/buildx/store imports
        github.com/gofrs/flock tested by
        github.com/gofrs/flock.test imports
        gopkg.in/check.v1 loaded from gopkg.in/check.v1@v1.0.0-20200227125254-8fa46927fb4f,
        but go 1.16 would select v1.0.0-20201130134442-10cb98267c6c

    To upgrade to the versions selected by go 1.16:
        go mod tidy -go=1.16 && go mod tidy -go=1.17
    If reproducibility with go 1.16 is not needed:
        go mod tidy -compat=1.17
    For other options, see:
        https://golang.org/doc/modules/pruning

### CODE REVIEW

**Comment by thaJeztah** [comment]
LOL. just opened this branch earlier to do so 😂 
Let me get back to doing that

**Comment by thaJeztah** [comment]
done!

**Review by crazy-max — APPROVED** [review]
LGTM, PTAL @tonistiigi

**Comment by crazy-max** [comment]
@thaJeztah Sorry can you rebase again? There was some flakiness with e2e tests that have been fixed, thx!

**Comment by thaJeztah** [comment]
Sure, no worries; done!

**Review by crazy-max — APPROVED** [review]
LGTM thanks, PTAL @tonistiigi

**Review by tonistiigi — APPROVED** [review]

**Pull request merged**
