### PR TITLE
vendor: github.com/theupdateframework/notary v0.7.0

### PR DESCRIPTION
**Pull request by thaJeztah**
update the dependency to v0.7.0 to be closer to what docker/cli uses; https://github.com/theupdateframework/notary/compare/v0.6.1...v0.7.0

Note that docker/cli is slightly ahead of v0.7.0, and uses bf96a202a09a; https://github.com/theupdateframework/notary/compare/v0.7.0...bf96a202a09a

### CODE REVIEW

**Comment by crazy-max** [comment]
> Is GitHub actions unhappy?
> 
> ```
> Prepare all required actions
> Getting action download info
> Download action repository 'actions/checkout@v3' (SHA:f43a0e5ff2bd294095638e18286ca9a3d1956744)
> Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_6d86f452-e5d9-40ce-a61a-6ac9b99b2666/33134418-a988-41c0-a13c-a6b6ebd982e6.tar.gz. return code: 2.
> ```

Yes indeed: https://github.com/actions/checkout/issues/1448

**Comment by thaJeztah** [comment]
Looks like it barfs when running things in parallel, but it works when running checks individually 🤔

**Comment by crazy-max** [comment]
We could probably bump to v4 but let's wait, might be transient.

**Comment by crazy-max** [comment]
Just curious but do you know why there is no v0.7.0 GH release of notary?

**Review by crazy-max — APPROVED** [review]

**Comment by thaJeztah** [comment]
> Just curious but do you know why there is no v0.7.0 GH release of notary?

No, I don't, but I'm guessing it's just because things are very slow in that repo

**Comment by thaJeztah** [comment]
@tonistiigi PTAL 🤗

**Review by tonistiigi — APPROVED** [review]

**Pull request merged**
