### PR TITLE
set --ssh default when omitted

### PR DESCRIPTION
**Pull request by alexcb**
this fixes https://github.com/moby/buildkit/issues/1035

Signed-off-by: Alex Couture-Beil <alex@mofo.ca>

### CODE REVIEW

**Comment by tonistiigi** [comment]
No, `--ssh default` is considered insecure if it is added without any opt-in by the user. But going back to https://github.com/moby/buildkit/issues/1035 I think we can consider the user using `git@` ssh address in context as equivalent opt-in (when user does not specify other ssh config).

**Comment by tonistiigi** [comment]
@alexcb Not `in.buildArgs` but `contextPath`. Otherwise sgtm. There is also bake command, if you can you can look into covering that as well.

**Comment by alexcb** [comment]
@tonistiigi I was hoping to use https://github.com/moby/buildkit/blob/master/client/llb/source.go#L209 to do something like:

	sshSpecs := in.ssh
	if len(sshSpecs) == 0 && llb.getGitProtocol(in.contextPath) == llb.gitProtocolSSH {
		sshSpecs = []string{"default"}
	}
	ssh, err := build.ParseSSHSpecs(sshSpecs)
	...

However those aren't exported; How do you feel about me moving the git protocol detection code into a new buildkit util, under `buildkit/util/gitutil`?

**Comment by tonistiigi** [comment]
@alexcb sgtm

**Pull request closed without merging**
